Code Review - Improvements and/or Changes
Rysth/REACT-AppointWheels pull request #17
Opened 2023-12-12 21:06 UTC by Rebelzob

# Appoint Wheels

-

2023-12-12 23:28 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Nice code organization ✔️ 
-  Good readme ✔️ 
-  Nice, beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-13 17:24 UTC, Rebelzob commented on README.md
> +- Install the dependencies and start the server:
@Meltrust We appreciate your feedback, it feels like you dug deep into the project and that makes us feel really good.

2023-12-13 21:14 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Functions are now ES6✔️
-  Readme has been updated ✔️ 
-  Superfluous backend test folder has been removed✔️ 
-  Renting in the past has been fixed (only in "new rental" section) ✔️ 
-  It is possible now to access the admin functionality ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-13 21:14 UTC, Meltrust commented on src/components/pages/car/carDetailForm.jsx
> +const CarDetailForm = ({ car }) => {
- [ ] Good job adding validation for "new rentals" section.

However, in the car details section, I can still rent in the past:

![image](https://github.com/Rysth/REACT-AppointWheels/assets/57421823/81b6fdcb-c588-4770-97be-4d2ce0a5ccbf)

![image](https://github.com/Rysth/REACT-AppointWheels/assets/57421823/7dccda9e-ee6e-4be6-9afd-f1e4986941c2)

## Suggested solution

You are using React Datepicker by Hackerone.

Therefore, this is your solution from their documentation:

https://reactdatepicker.com/#example-min-date

![image](https://github.com/Rysth/REACT-AppointWheels/assets/57421823/3e8725b7-b006-4a19-94ff-1d2a99f0992a)

The `min-date` property will let you set a minimum date.  That way you can avoid reservations in the past. 

You can add the property here:

![image](https://github.com/Rysth/REACT-AppointWheels/assets/57421823/46a66a06-f8a8-4e90-bb5d-11adcf022729)

There is also an article that explains how to implement this:

https://medium.com/@ukaohachizoba6/how-to-disable-past-and-future-dates-with-react-date-picker-916f2fc6a9b7

![image](https://github.com/Rysth/REACT-AppointWheels/assets/57421823/70c71a32-2fb4-4a6f-9306-d9cb48ebf35a)


Now that you know the solution and the way to implement it, kindly, make it so it is simply not possible to rent in the past, even from the car details page. 💪

2023-12-13 22:29 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Beautiful, superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2023-12-14 14:49 UTC, merged